[build]
  command = "npm run build"
  publish = "dist"

# (optional) local dev proxy
[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 4321

# (optional) clean URLs / fallback for static routes you might add
# [[redirects]]
#   from = "/*"
#   to = "/404.html"
#   status = 404

[[headers]]
for = "/legal/*.pdf"
  [headers.values]
  Cache-Control = "public, max-age=31536000"