# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  # Safe default for local/CI. Netlify will override per-context below.
  PUBLIC_SITE_URL = "https://digissential.co.za"

[dev]
  command   = "npm run dev"
  port      = 8888
  targetPort = 4321

##########
# Redirects
##########

# Apex is canonical → send www → apex
[[redirects]]
  from = "https://www.digissential.co.za/*"
  to   = "https://digissential.co.za/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://digissential.co.za/*"
  to   = "https://digissential.co.za/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://www.digissential.co.za/*"
  to   = "https://digissential.co.za/:splat"
  status = 301
  force  = true


#############
# Security headers (production defaults)
#############
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; frame-src https://www.google.com https://www.google.co.za; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; frame-ancestors 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

#########################
# Caching (performance)
#########################

# Never cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Hashed build assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Fonts
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Icons
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "no-cache"

# Sitemaps (keep fresh)
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Cache-Control = "no-cache"

#####################################
# Context: production (main → live)
#####################################
[context.production.environment]
  PUBLIC_SITE_URL = "https://digissential.co.za"

#####################################
# Context: Deploy Previews (PRs)
#####################################
[context.deploy-preview.environment]
  # Netlify injects the preview URL — use it for canonicals/LD-JSON
  PUBLIC_SITE_URL = "$DEPLOY_PRIME_URL"

# Make *every* preview non-indexable
[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex, nofollow"

#####################################
# Context: Branch Deploys (e.g. staging)
#####################################
[context.branch-deploy.environment]
  PUBLIC_SITE_URL = "$DEPLOY_URL"

[context.branch-deploy]
  [[context.branch-deploy.headers]]
    for = "/*"
    [context.branch-deploy.headers.values]
      X-Robots-Tag = "noindex, nofollow"
